### ISSUE TITLE
CloudFormation 'default' and Lambd bug

### ISSUE THREAD

**Issue by gxvigo** [awstut-an-r/awstut-fa#1]
Hi There, 
Thanks for sharing this, good stuff.
I found a couple of issues:
- in CloudFormation stack Default must be String
- index.py missing 'db_endpoint_port = os.environ['DB_ENDPOINT_PORT']'

**Comment by awstut-an-r** [comment]
Thanks for your comment!
I have corrected the relevant codes in the repository.

●Before modification
db_endpoint_port = os.environ['DB_ENDPOINT_PORT']]

●After modification
db_endpoint_port = int(os.environ['DB_ENDPOINT_PORT'])

Thank you for your continued contribution.
